version: '3.8'
services:
  dev-valentin-bzh:
    image: php:8.2-apache
    container_name: dev-valentin-bzh
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/app
    networks:
      - dev-valentin-bzh
    restart: unless-stopped

networks:
  dev-valentin-bzh:
    external: true
