services:
  dev-valentin-bzh:
    build:
      context: .
      network: host
    container_name: dev-valentin-bzh
    volumes:
      - ./logs:/var/log/app
    networks:
      - dev-valentin-bzh
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.5

networks:
  dev-valentin-bzh:
    external: true
